#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
03_scaffold.py — Remotion project scaffolder for video-production

Initializes or refreshes a Remotion project directory from a storyboard.json.
Creates all structural files (package.json, tsconfig.json, src/config.ts,
src/index.ts, src/Root.tsx, scene stubs) and updates the parent .gitignore.
Runs npm install at the end.

Usage:
    uv run 03_scaffold.py \\
        --project-dir path/to/remotion-infographic \\
        --fps 30 \\
        --width 1080 \\
        --height 1920 \\
        --storyboard path/to/storyboard.json

Re-running is safe: it will NOT overwrite existing scene TSX files
(those contain real agent-authored composition code). It WILL overwrite
package.json, tsconfig.json, src/config.ts, src/index.ts, and src/Root.tsx
if they already exist — these are generated from storyboard data.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from textwrap import dedent


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Scaffold a Remotion project from a storyboard.json.")
    p.add_argument("--project-dir", required=True, help="Path to the remotion project directory (created if absent).")
    p.add_argument("--storyboard", required=True, help="Path to storyboard.json.")
    p.add_argument("--fps", type=int, default=30, help="Frames per second (default: 30).")
    p.add_argument("--width", type=int, default=1080, help="Frame width in pixels (default: 1080).")
    p.add_argument("--height", type=int, default=1920, help="Frame height in pixels (default: 1920).")
    p.add_argument("--remotion-version", default="4.0.0", help="Remotion package version to pin (default: 4.0.0).")
    p.add_argument("--skip-install", action="store_true", help="Skip npm install (useful for dry-run inspection).")
    return p.parse_args()


# ---------------------------------------------------------------------------
# File content generators
# ---------------------------------------------------------------------------

def make_package_json(version: str, total_frames: int) -> str:
    last_frame = max(0, total_frames - 1)
    data = {
        "name": "video-production",
        "version": "1.0.0",
        "private": True,
        "scripts": {
            "studio": "npx remotion studio src/index.ts",
            "typecheck": "tsc --noEmit",
            "render": f"npx remotion render src/index.ts VideoFull out/video.mp4 --codec=h264 --pixel-format=yuv420p",
            "hero": f"npx remotion still src/index.ts VideoFull out/video-hero.png --frame={last_frame}",
        },
        "dependencies": {
            "remotion": version,
            "@remotion/media": version,
            "@remotion/captions": version,
            "react": "18.3.1",
            "react-dom": "18.3.1",
        },
        "devDependencies": {
            "typescript": "5.4.0",
            "@types/react": "18.3.1",
        },
    }
    return json.dumps(data, indent=2)


def make_tsconfig() -> str:
    data = {
        "compilerOptions": {
            "target": "ES2020",
            "module": "ESNext",
            "moduleResolution": "bundler",
            "jsx": "react",
            "strict": True,
            "resolveJsonModule": True,
            "esModuleInterop": True,
            "outDir": "dist",
        },
        "include": ["src"],
    }
    return json.dumps(data, indent=2)


def make_config_ts(fps: int, width: int, height: int, scenes: list[dict]) -> str:
    scenes_ts = json.dumps(
        [
            {
                "id": f"Scene{s['scene']}",
                "durationFrames": s["duration_frames"],
                "audioFile": f"audio/{s['audio_file']}",
                "timestampsFile": f"audio/{s['timestamps_file']}",
                "title": s.get("title", f"Scene {s['scene']}"),
            }
            for s in scenes
        ],
        indent=2,
    )
    total = sum(s["duration_frames"] for s in scenes)
    return dedent(f"""\
        // src/config.ts
        // Auto-generated by 03_scaffold.py — re-run scaffold to refresh after storyboard changes.

        export const VIDEO_CONFIG = {{
          fps: {fps},
          width: {width},
          height: {height},
        }} as const;

        export interface SceneConfig {{
          id: string;
          durationFrames: number;
          audioFile: string;
          timestampsFile: string;
          title: string;
        }}

        export const SCENES: SceneConfig[] = {scenes_ts};

        export const TOTAL_FRAMES = SCENES.reduce((sum, s) => sum + s.durationFrames, 0);
        export const LAST_FRAME = TOTAL_FRAMES - 1;
    """)


def make_index_ts() -> str:
    return dedent("""\
        import { registerRoot } from "remotion";
        import { Root } from "./Root";
        registerRoot(Root);
    """)


def make_root_tsx(scenes: list[dict]) -> str:
    imports = "\n".join(
        f'import {{ Scene{s["scene"]} }} from "./scenes/Scene{s["scene"]}";' for s in scenes
    )
    series_sequences = "\n".join(
        f'      <Series.Sequence durationInFrames={{SCENES[{i}].durationFrames}}>\n'
        f'        <Scene{s["scene"]} />\n'
        f'      </Series.Sequence>'
        for i, s in enumerate(scenes)
    )
    scene_compositions = "\n".join(
        f'    <Composition\n'
        f'      id="Scene{s["scene"]}"\n'
        f'      component={{Scene{s["scene"]}}}\n'
        f'      durationInFrames={{SCENES[{i}].durationFrames}}\n'
        f'      fps={{VIDEO_CONFIG.fps}}\n'
        f'      width={{VIDEO_CONFIG.width}}\n'
        f'      height={{VIDEO_CONFIG.height}}\n'
        f'    />'
        for i, s in enumerate(scenes)
    )
    return dedent(f"""\
        import React from "react";
        import {{ Composition, Series }} from "remotion";
        import {{ VIDEO_CONFIG, SCENES, TOTAL_FRAMES }} from "./config";
        {imports}

        const VideoFull: React.FC = () => (
          <Series>
        {series_sequences}
          </Series>
        );

        export const Root: React.FC = () => (
          <>
            {{/* Master composition — full merged video */}}
            <Composition
              id="VideoFull"
              component={{VideoFull}}
              durationInFrames={{TOTAL_FRAMES}}
              fps={{VIDEO_CONFIG.fps}}
              width={{VIDEO_CONFIG.width}}
              height={{VIDEO_CONFIG.height}}
            />
            {{/* Per-scene compositions for isolated preview rendering */}}
        {scene_compositions}
          </>
        );
    """)


def make_scene_stub(scene: dict) -> str:
    n = scene["scene"]
    title = scene.get("title", f"Scene {n}")
    bg = scene.get("visual_direction", {}).get("background", "#0f172a")
    return dedent(f"""\
        // src/scenes/Scene{n}.tsx
        // Scene {n}: {title}
        // TODO: Implement this scene using the visual_direction from storyboard.json.
        // Replace the placeholder elements below with real animated composition.

        import React from "react";
        import {{ Audio, useCurrentFrame, useVideoConfig, interpolate }} from "remotion";
        import {{ staticFile }} from "remotion";
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-expect-error — JSON import requires resolveJsonModule:true
        import timestampData from "../../public/audio/scene-{n}-timestamps.json";

        const HOLD_FRAMES = {scene.get("hold_frames", 15)};

        export const Scene{n}: React.FC = () => {{
          const frame = useCurrentFrame();
          const {{ fps, width, height }} = useVideoConfig();

          // Fade in the heading over the first 12 frames
          const opacity = interpolate(frame, [0, 12], [0, 1], {{
            extrapolateLeft: "clamp",
            extrapolateRight: "clamp",
          }});
          const translateY = interpolate(frame, [0, 12], [30, 0], {{
            extrapolateLeft: "clamp",
            extrapolateRight: "clamp",
          }});

          return (
            <div
              style={{{{
                width,
                height,
                background: "{bg}",
                position: "relative",
                overflow: "hidden",
                fontFamily: "sans-serif",
              }}}}
            >
              {{/* Voiceover audio */}}
              <Audio src={{staticFile("audio/scene-{n}.wav")}} />

              {{/* Heading — replace with storyboard visual_direction.elements */}}
              <div
                style={{{{
                  position: "absolute",
                  top: "30%",
                  left: 48,
                  right: 48,
                  opacity,
                  transform: `translateY(${{translateY}}px)`,
                  fontSize: 64,
                  fontWeight: "bold",
                  color: "#f0f9ff",
                  lineHeight: 1.2,
                }}}}
              >
                {title}
              </div>

              {{/*
                TODO: Add @remotion/captions <Captions> component here.
                Pass timestampData.words and currentTime = frame / fps.
                See references/video-production-pipeline.md §5 for the pattern.
              */}}
            </div>
          );
        }};
    """)


# ---------------------------------------------------------------------------
# Gitignore helper
# ---------------------------------------------------------------------------

GITIGNORE_RULES = """
# Video production assets (large models, not for version control)
.video_production_assets/

# Local Remotion video production workspaces
**/remotion-infographic/
**/remotion-infographic/*
"""


def update_gitignore(project_dir: Path) -> None:
    """Walk up from project_dir to find a .gitignore and add rules if not present."""
    search = project_dir.parent
    for _ in range(6):  # cap the search depth
        gi = search / ".gitignore"
        if gi.exists() or (search / ".git").exists():
            existing = gi.read_text(encoding="utf-8") if gi.exists() else ""
            new_rules: list[str] = []
            for line in GITIGNORE_RULES.strip().splitlines():
                if line and line not in existing:
                    new_rules.append(line)
            if new_rules:
                with gi.open("a", encoding="utf-8") as f:
                    f.write("\n" + "\n".join(new_rules) + "\n")
                print(f"Updated .gitignore at: {gi}")
            else:
                print(f".gitignore at {gi} already contains all required rules.")
            return
        parent = search.parent
        if parent == search:
            break
        search = parent
    # No .gitignore found — write one beside the project directory
    gi = project_dir.parent / ".gitignore"
    gi.write_text(GITIGNORE_RULES.strip() + "\n", encoding="utf-8")
    print(f"Created .gitignore at: {gi}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    args = parse_args()
    project_dir = Path(args.project_dir).expanduser().resolve()
    storyboard_path = Path(args.storyboard).expanduser().resolve()

    if not storyboard_path.exists():
        print(f"ERROR: storyboard.json not found: {storyboard_path}", file=sys.stderr)
        sys.exit(1)

    storyboard: list[dict] = json.loads(storyboard_path.read_text(encoding="utf-8"))
    if not storyboard:
        print("ERROR: storyboard.json is empty.", file=sys.stderr)
        sys.exit(1)

    # Validate required fields
    for s in storyboard:
        for field in ("scene", "duration_frames", "audio_file", "timestamps_file"):
            if field not in s:
                print(f"ERROR: scene {s.get('scene', '?')} missing required field '{field}'", file=sys.stderr)
                sys.exit(1)

    total_frames = sum(s["duration_frames"] for s in storyboard)
    print(f"Scaffolding Remotion project at: {project_dir}")
    print(f"  {len(storyboard)} scene(s), {total_frames} total frames @ {args.fps} fps")

    # Create directory tree
    (project_dir / "src" / "scenes").mkdir(parents=True, exist_ok=True)
    (project_dir / "public" / "audio").mkdir(parents=True, exist_ok=True)
    (project_dir / "out" / "scenes").mkdir(parents=True, exist_ok=True)

    # Write generated files (always overwrite)
    def write(path: Path, content: str) -> None:
        path.write_text(content, encoding="utf-8")
        print(f"  Wrote: {path.relative_to(project_dir)}")

    write(project_dir / "package.json", make_package_json(args.remotion_version, total_frames))
    write(project_dir / "tsconfig.json", make_tsconfig())
    write(project_dir / "src" / "config.ts", make_config_ts(args.fps, args.width, args.height, storyboard))
    write(project_dir / "src" / "index.ts", make_index_ts())
    write(project_dir / "src" / "Root.tsx", make_root_tsx(storyboard))

    # Write scene stubs — only for files that do not yet exist
    for scene in storyboard:
        n = scene["scene"]
        scene_path = project_dir / "src" / "scenes" / f"Scene{n}.tsx"
        if scene_path.exists():
            print(f"  Skipped (already exists): src/scenes/Scene{n}.tsx")
        else:
            write(scene_path, make_scene_stub(scene))

    # Update .gitignore
    update_gitignore(project_dir)

    # npm install
    if args.skip_install:
        print("Skipping npm install (--skip-install).")
    else:
        pkg_manager = "pnpm" if _which("pnpm") else "npm"
        print(f"\nRunning {pkg_manager} install in {project_dir}...")
        result = subprocess.run([pkg_manager, "install"], cwd=project_dir, check=False)
        if result.returncode != 0:
            print(f"ERROR: {pkg_manager} install failed with code {result.returncode}.", file=sys.stderr)
            sys.exit(result.returncode)
        print(f"{pkg_manager} install completed successfully.")

    print(f"\nScaffold complete. Project ready at: {project_dir}")
    print("Next step: implement each SceneN.tsx using the storyboard visual_direction.")


def _which(cmd: str) -> bool:
    """Return True if `cmd` is on PATH."""
    import shutil
    return shutil.which(cmd) is not None


if __name__ == "__main__":
    main()

